apiVersion: apps/v1
kind: Deployment
metadata:
  name: voter-selfcheck
spec:
  replicas: 1
  selector:
    matchLabels:
      name: voter-selfcheck
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata: 
      labels:
        name: voter-selfcheck
    spec:
      containers:
      - name: voterselfcheck-benchmark
        image: voltdb/voter-selfcheck:latest
        imagePullPolicy: Always
        envFrom:
          - configMapRef:
              name: voterselfcheck-config
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      imagePullSecrets:
      - name: dockerio-registry